server:
  port: 8033
  shutdown: graceful

spring:
  application:
    name: coin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.31.16.56:5432/upbit
    username: postgres
    password: "Antock1026!!"
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false

upbit:
  url: "https://api.upbit.com/v1/"
  access-key: "8eKH4vW7R1FqMgWx0l8aEkcuPH0EjZcJ8bbWj6xG"
  secret-key: "oxirtdRobtJQSnmXixWYloqcxuh1xId9AzAwtPSF"


kakao:
  url: "https://kauth.kakao.com/oauth/token"
  msgUrl : "https://kapi.kakao.com/v2/api/talk/memo/default/send"
  client-id: "8225bdeb86e298026db8e32e510f23f6"
  redirect-uri: "http://localhost:8033"
  client-secret: "r0kGmGyVufH3w7nUnNMFKeuVgqBgSFJZ"